title: Gavin Pryor
logo: /assets/img/portfolio_headshot.png
description: My name is Gavin Pryor and I am a second-year student at the University of Pittsburgh. 
I am pursuing a degree in Data Analytics, with minors in Computer Science and Statistics.
I am interested in the applications and implementation of emerging technologies, AI and LLMs, data 
science and analysis, and the monetization of data. I am currently crafting my coursework, internship 
experience, and project portfolio to combine programming and data science skills with business acumen 
to provide me with a well-rounded skillset and knowledge of the tech ecosystem. Eventually, I want to 
leverage these skills and the power of emerging technologies for social good and make a positive impact 
on society by improving the industry and lives of others. Other personal passions of mine are basketball 
and sports, music and piano, traveling, and trying new foods from different cultures. Please do not hesitate to reach out!
theme: jekyll-theme-minimal
