title: Gavin Pryor
logo: /assets/img/portfolio_headshot.png
description: tejigeojpjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
theme: jekyll-theme-minimal
